apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../definitions/argo-hardening/application-overlay

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: argocd-self
      namespace: argocd
    patch: |-
      - op: replace
        path: /spec/sources/1/path
        value: gitops/platform/management/protection-foundation/activation/personal-local-observing/argocd-self-base-overlay
