apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../argocd-self/base

patches:
  - target:
      version: v1
      kind: ConfigMap
      name: argocd-cm
      namespace: argocd
    patch: |-
      - op: add
        path: /data/admin.enabled
        value: "false"
      - op: add
        path: /data/users.anonymous.enabled
        value: "false"
