apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Application
      name: platform-control
    patch: |-
      - op: replace
        path: /spec/source/path
        value: gitops/platform/applications/overlays/local-orbstack
  - target:
      kind: Application
      name: workload-control
    patch: |-
      - op: replace
        path: /spec/source/path
        value: gitops/workloads/applications/overlays/local-orbstack
