apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster

networking:
  ipFamily: ipv4
  apiServerAddress: 127.0.0.1

containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry]
      config_path = "/etc/containerd/certs.d"

nodes:
  - role: control-plane
    labels:
      atlas.io/node-pool: control
  - role: worker
    labels:
      atlas.io/node-pool: gateway
  - role: worker
    labels:
      atlas.io/node-pool: compute
  - role: worker
    labels:
      atlas.io/node-pool: data
    kubeadmConfigPatches:
      - |-
        apiVersion: kubeadm.k8s.io/v1beta4
        kind: JoinConfiguration
        nodeRegistration:
          taints:
            - key: atlas.io/node-pool
              value: data
              effect: NoSchedule
